import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#d4e3ff",
        "secondary-fixed-dim": "#ffb86a",
        secondary: "#895200",
        "secondary-container": "#fda945",
        "on-tertiary-fixed": "#001d35",
        "on-tertiary-container": "#7390b2",
        outline: "#74777f",
        "secondary-fixed": "#ffdcbc",
        "surface-tint": "#436087",
        "on-surface-variant": "#43474e",
        "tertiary-fixed-dim": "#abc9ee",
        "on-error-container": "#93000a",
        background: "#fcf9f4",
        "surface-dim": "#dcdad5",
        "tertiary-container": "#032845",
        "inverse-surface": "#31302d",
        "surface-bright": "#fcf9f4",
        "inverse-primary": "#abc8f5",
        primary: "#001229",
        "on-primary-container": "#738fb9",
        "on-background": "#1c1c19",
        "error-container": "#ffdad6",
        "surface-container-high": "#ebe8e3",
        "inverse-on-surface": "#f3f0eb",
        "on-secondary-fixed-variant": "#683d00",
        "on-secondary": "#ffffff",
        "on-surface": "#1c1c19",
        "surface-container-low": "#f6f3ee",
        "primary-fixed-dim": "#abc8f5",
        "surface-variant": "#e5e2dd",
        "surface-container-highest": "#e5e2dd",
        "primary-container": "#02274b",
        surface: "#fcf9f4",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "tertiary-fixed": "#d0e4ff",
        "surface-container-lowest": "#ffffff",
        tertiary: "#001325",
        "surface-container": "#f0ede8",
        "on-secondary-container": "#6e4100",
        "outline-variant": "#c3c6cf",
        "on-primary-fixed-variant": "#2b486d",
        "on-secondary-fixed": "#2c1700",
        "on-tertiary-fixed-variant": "#2b4967",
        "on-primary-fixed": "#001c39",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
      },
      fontFamily: {
        headline: ["var(--font-plus-jakarta-sans)"],
        body: ["var(--font-plus-jakarta-sans)"],
        label: ["var(--font-plus-jakarta-sans)"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
export default config;
